### PR TITLE
DOC: Dev Env docs in README

### LINKED ISSUE #49: Update README with dev env setup and local testing instructions

### LINKED ISSUE #53: Add Gemfile

### PR DESCRIPTION
**Pull request by thermokarst**
[Rendered.](https://github.com/thermokarst/caporaso-lab.github.io/blob/de73b53df1474cbf0ed72c3a97fe19c698c3678a/README.md)

---

Fixes #49.
Fixes #53.

### CODE REVIEW

**Comment by jakereps** [comment]
To guarantee working dev-mode -> GitHub pages translation, these lines should be added to a `Gemfile`: https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/#step-2-install-jekyll-using-bundler

**Comment by thermokarst** [comment]
Thanks @jakereps - probably need a Gemfile, first! (#53)

**Comment by thermokarst** [comment]
@turanoo & @ChrisKeefe - want to try and test this new README out locally? See link above for the rendered file. Thanks!

**Comment by thermokarst** [comment]
As well, you will need to pull down the branch that is backing this PR, that way you have the files needed to test with. Hint, the PR is on the `issue-49` branch of [my fork](https://github.com/thermokarst/caporaso-lab.github.io).

**Comment by turanoo** [comment]
@thermokarst, everything looks great to me! Thank you 🎊

**Comment by thermokarst** [comment]
Thanks for looking into this @jakereps, @turanoo, and @ChrisKeefe! Discussed out-of-band - I am going to close this PR as is, in favor of a simplified environment setup approach (this will assume a little more one-on-one interaction between mentor and mentored), at @ebolyen's recommendation. Will follow up with another PR or two shortly. Thanks! 🎤 ⬇️

**Pull request closed without merging**
