### PR TITLE
MAINT: Remove projects tab

### PR DESCRIPTION
**Pull request by Oddant1**
Remove the projects tab from the top bar. Based on how this is implemented, it seems like all we should have to do is remove the file the projects tab links to, but I must be missing something. Removing the file does cause the tab to go away, but it also inexplicably causes the teaching tab to move down.
___
Screenshot from 2020-06-04 15-57-17
___
This never happens on anything but the homepage of my locally hosted site.
___
Screenshot from 2020-06-04 16-12-14
___
Sometimes if I click around between tabs on the site then go back to the homepage it's not wrapped, only to be wrapped again when I click away and back another time. I can't find any discernible pattern that always fixes it or anything. No idea why this is happening.
___
Screenshot from 2020-06-04 16-14-14
___
And the real kicker. Before removing the page for the projects tab the first time I swear this never happened (though I didn't click around too much so maybe it would have, and I just didn't see it) but now, after having removed the tab once, when I bring it back SOMETIMES THE BAR STILL WRAPS.
___
Screenshot from 2020-06-04 16-16-23
___
This wrapping obviously doesn't occur on the live version of the site.
___
Screenshot from 2020-06-04 16-18-58
___
I don't know what's going on here, but hopefully I'll be able to find some answers tomorrow. Hopefully this is just some stupid thing to do with my local hosting and is actually a non-issue :crossed_fingers:

### CODE REVIEW

**Comment by Oddant1** [comment]
I went ahead and copied the caporaso-lab/caporaso-lab.github.io to another new location on my machine, so I would have a completely untouched version and the wrapping still happened when I clicked around. So I don't think the wrapping is a real problem, jut something goofy happening when I host the site that shouldn't happen on the deployed site (maybe it has to do with local hosting via jekyll compared to whatever exactly is happening to deploy the site?).

**Review by thermokarst — CHANGES_REQUESTED** [review]
I think you will also need to update this file:

https://github.com/caporaso-lab/caporaso-lab.github.io/blob/master/_data/navigation.yml

**Comment by Oddant1** [comment]
I removed some more mentions of projects, and some more data associated with that page. This doesn't seem to have fixed the issue with the wrapping. At this point I think that really is just something goofy going on with the local hosting

**Review by thermokarst — APPROVED** [review]

**Comment by thermokarst** [comment]
> At this point I think that really is just something goofy going on with the local hosting

Who knows... I just pulled down locally, all appears to be working just fine. I'll go ahead and merge, but let me know if the wrapping is an issue for you on the live site (it'll take a few minutes for GH Pages to render and deploy).

**Comment by Oddant1** [comment]
@thermokarst I tested a few different environments and the wrapping is happening on the live page in all of them. It seems to behave differently on the live page. When I was hosting locally, it would happen just about every time I loaded the main page. On the live site now it's only happening when I first open the page. If I click to a different tab then back to the main page the wrapping always seems to go away. Same if I just sit there clicking on the homepage button over and over.

EDIT: It doesn't even wrap every time I initially load the page. It's extremely inconsistent.

**Comment by thermokarst** [comment]
> I tested a few different environments and the wrapping is happening on the live page in all of them

Is this a browser issue? I'm not seeing anything on my end. Can you check your JS console and make sure you're not getting any errors there?

**Comment by Oddant1** [comment]
@thermokarst I'm not getting it now either. So weird. I even went onto my desktop and tried on Firefox and Chromium on Linux then Firefox, Chrome, Edge, and even Internet Explorer on Windows and it happened on literally all of them. Now it's not. So I guess it went away.

**Pull request merged**
