### PR TITLE
MAINT: Fall 2017 Roster Updates

### PR DESCRIPTION
**Pull request by thermokarst**
Not sure what @jakereps title is these days, so feel free to let me know and I can make that change here.

screen shot 2017-10-27 at 17 42 42-fullpage

### CODE REVIEW

**Review by jairideout — APPROVED** [review]
Thanks for these updates @thermokarst! @jakereps can you let @thermokarst know if your bio needs any tweaks?

**Comment by jakereps** [comment]
As far as my bio, I had these bullet points: https://github.com/caporaso-lab/caporaso-lab.github.io/commit/2b281ff50766db918910c0e7746ad52cb71cbabc#diff-cae0f3940920ef2bda0b377bf60f9650. 

For a title, I really don't know what that is at the moment?

**Comment by thermokarst** [comment]
Thanks @jakereps & @jairideout, updated!

**Comment by jairideout** [comment]
> For a title, I really don't know what that is at the moment?

I pinged @gregcaporaso on that, will follow up when I hear back.

**Comment by jairideout** [comment]
Heard back from @gregcaporaso, let's go with *Research Software Engineer* for @jakereps' position. @thermokarst can you make that update and I'll merge?

**Comment by thermokarst** [comment]
Thanks @jairideout! Done!

**Review by jairideout — APPROVED** [review]
Thanks @thermokarst!!

**Comment by jakereps** [comment]
Thanks guys!

**Pull request merged**
