### PR TITLE
MAINT: misc updates

### PR DESCRIPTION
**Pull request by gregcaporaso**

### CODE REVIEW

**Comment by lizgehret** [comment]
Congrats on RSE II @colinvwood 🥳

**Comment by lizgehret** [comment]
@gregcaporaso just pulled this down locally and have one comment - 'research software engineering' takes up a wider horizontal segment than your profile picture, so it looks like your interests include 'research software' and 'engineering'. Not sure if we should adjust the width or if you're okay with this?
Screen Shot 2023-09-28 at 2 34 29 PM

**Comment by gregcaporaso** [comment]
Thanks for catching that @lizgehret! I updated to shorten that entry. Though if a wider area for this wouldn't be more trouble than it's worth, maybe we can do that and scrub that last commit? (No rush on this at all.)

**Comment by lizgehret** [comment]
I modified the allowed width for each team member, which would look like this with `research software engineering` added as your third interest. Are you okay with how that looks? It's a bit wider than the team photos, but I'd have to increase the size of everyone's photos to make that interest line up with them, since most of them were added at 200px originally. Let me know what you'd prefer!

Screen Shot 2023-10-03 at 11 03 40 AM

**Comment by gregcaporaso** [comment]
@lizgehret, I reduced the size of that text slightly. How's this:
Screenshot 2023-10-05 at 9 40 31 AM

**Comment by lizgehret** [comment]
This adjustment looks good, ~~should we modify the past team members' interests text size to match? Sorry we're kind of getting into the weeds with this one~~ - disregard, everything looks good here! I'll go ahead and merge!

**Pull request merged**
