### PR TITLE
Add Dillon to team!

### PR DESCRIPTION
**Pull request by thermokarst**
Not sure if the personnel list should be in a particular order, but for now I just snagged the spot between Jai and Arron. Thanks!

### CODE REVIEW

**Comment by jairideout** [comment]
Thanks @thermokarst! We have the names in alphabetical order by last name (except for Greg). Can you move your profile between Evan and Kestrel? This is ready for merge after that.

**Comment by thermokarst** [comment]
@jairideout: thanks! I figured that was the case, but didn't want to be _that guy_ that goes moving everyone else around ("excuse me excuse me, coming through!")

667bbe1 reflects the new ordering.

**Comment by jairideout** [comment]
Awesome, thanks @thermokarst!

**Comment by jairideout** [comment]
Changes are live:

http://caporasolab.us/team/

**Pull request merged**
